### PR TITLE
Update users.js to get on the board

### PR DESCRIPTION
**Pull request by pthomas931**
Hopefully this repo is open to friends

### CODE REVIEW

**Comment by cogwizzle** [comment]
Ha ha unfortunately it is not open to friends.  I can fork the repository and spin up a new surge site.  MR is valid, but not desired functionality.  I'll leave it marked as valid so you get credit.

**Comment by pthomas931** [comment]
No worries, thanks for checking!

**Comment by cogwizzle** [comment]
I'll open a branch this afternoon and push it up to surge.  Stand by for another Pull Request.

**Comment by cogwizzle** [comment]
Their is a friends branch.  The friends branch points to friends-hacktoberfest-2020.surge.sh.  You can add your name to the users.js list and push to that branch.

**Pull request closed without merging**
